#!/bin/bash

INST_LOG="/var/log/apps/${TRIM_APPNAME}.log"
FWPORTS_FILE="/var/apps/${TRIM_APPNAME}/etc/${TRIM_APPNAME}.sc"
TMP_DIR="${TRIM_TEMP_UPGRADE_FOLDER}"

COMMON=$(dirname $0)"/common"
if [ -r "${COMMON}" ]; then
    . "${COMMON}"
fi

SVC_SETUP=$(dirname $0)"/service-setup"
if [ -r "${SVC_SETUP}" ]; then
    . "${SVC_SETUP}"
fi

load_variables_from_file ${INST_VARIABLES}
call_func "initialize_variables" install_log
